export type Word = {
  dutch: string;
  english: string;
  difficulty: "easy" | "medium" | "hard";
};

export const wordList: Word[] = [
  { dutch: "absoluut", english: "absolutely", difficulty: "easy" },
  { dutch: "accepteren", english: "to accept", difficulty: "easy" },
  { dutch: "actie", english: "action", difficulty: "easy" },
  { dutch: "actief", english: "active", difficulty: "easy" },
  { dutch: "activiteit", english: "activity", difficulty: "easy" },
  { dutch: "adres", english: "address", difficulty: "easy" },
  { dutch: "advies", english: "advice", difficulty: "easy" },
  { dutch: "agent", english: "agent", difficulty: "easy" },
  { dutch: "al", english: "already", difficulty: "easy" },
  { dutch: "alle", english: "all", difficulty: "easy" },
  { dutch: "alleen", english: "only", difficulty: "easy" },
  { dutch: "als", english: "if/when", difficulty: "easy" },
  { dutch: "ander", english: "other", difficulty: "easy" },
  { dutch: "antwoord", english: "answer", difficulty: "easy" },
  { dutch: "arm", english: "arm", difficulty: "easy" },
  { dutch: "artikel", english: "article", difficulty: "easy" },
  { dutch: "aspect", english: "aspect", difficulty: "easy" },
  { dutch: "auteur", english: "author", difficulty: "easy" },
  { dutch: "automatisch", english: "automatically", difficulty: "easy" },
  { dutch: "baby", english: "baby", difficulty: "easy" },
  { dutch: "baas", english: "boss", difficulty: "easy" },
  { dutch: "bank", english: "bank", difficulty: "easy" },
  { dutch: "basis", english: "base", difficulty: "easy" },
  { dutch: "bed", english: "bed", difficulty: "easy" },
  { dutch: "beide", english: "both", difficulty: "easy" },
  { dutch: "beïnvloeden", english: "to influence", difficulty: "easy" },
  { dutch: "begin", english: "get started", difficulty: "easy" },
  { dutch: "beginnen", english: "to begin", difficulty: "easy" },
  { dutch: "bespreken", english: "discuss", difficulty: "easy" },
  { dutch: "beter", english: "better", difficulty: "easy" },
  { dutch: "bezig", english: "busy", difficulty: "easy" },
  { dutch: "bier", english: "beer", difficulty: "easy" },
  { dutch: "bijten", english: "to bite", difficulty: "easy" },
  { dutch: "bitter", english: "bitter", difficulty: "easy" },
  { dutch: "blauw", english: "blue", difficulty: "easy" },
  { dutch: "bloed", english: "blood", difficulty: "easy" },
  { dutch: "bodem", english: "bottom", difficulty: "easy" },
  { dutch: "boek", english: "book", difficulty: "easy" },
  { dutch: "boot", english: "boat", difficulty: "easy" },
  { dutch: "breng", english: "bring", difficulty: "easy" },
  { dutch: "broer", english: "brother", difficulty: "easy" },
  { dutch: "brood", english: "bread", difficulty: "easy" },
  { dutch: "bruin", english: "brown", difficulty: "easy" },
  { dutch: "bus", english: "bus", difficulty: "easy" },
  { dutch: "café", english: "cafe", difficulty: "easy" },
  { dutch: "categorie", english: "category", difficulty: "easy" },
  { dutch: "centrum", english: "centre", difficulty: "easy" },
  { dutch: "collega", english: "colleague", difficulty: "easy" },
  { dutch: "combinatie", english: "combination", difficulty: "easy" },
  { dutch: "communicatie", english: "communication", difficulty: "easy" },
  { dutch: "computer", english: "computer", difficulty: "easy" },
  { dutch: "conclusie", english: "conclusion", difficulty: "easy" },
  { dutch: "consequentie", english: "consequence", difficulty: "easy" },
  { dutch: "contact", english: "contact", difficulty: "easy" },
  { dutch: "crisis", english: "crisis", difficulty: "easy" },
  { dutch: "cultureel", english: "cultural", difficulty: "easy" },
  { dutch: "cultuur", english: "culture", difficulty: "easy" },
  { dutch: "daar", english: "there", difficulty: "easy" },
  { dutch: "dag", english: "day", difficulty: "easy" },
  { dutch: "dan", english: "then", difficulty: "easy" },
  { dutch: "danken", english: "to thank", difficulty: "easy" },
  { dutch: "dansen", english: "to dance", difficulty: "easy" },
  { dutch: "dat", english: "that", difficulty: "easy" },
  { dutch: "de", english: "the", difficulty: "easy" },
  { dutch: "deel", english: "part", difficulty: "easy" },
  { dutch: "denken", english: "to think", difficulty: "easy" },
  { dutch: "derde", english: "third", difficulty: "easy" },
  { dutch: "deze", english: "this", difficulty: "easy" },
  { dutch: "diep", english: "deep", difficulty: "easy" },
  { dutch: "ding", english: "thing", difficulty: "easy" },
  { dutch: "direct", english: "directly", difficulty: "easy" },
  { dutch: "directeur", english: "director", difficulty: "easy" },
  { dutch: "discussie", english: "discussion", difficulty: "easy" },
  { dutch: "dit", english: "this", difficulty: "easy" },
  { dutch: "dochter", english: "daughter", difficulty: "easy" },
  { dutch: "doen", english: "to do", difficulty: "easy" },
  { dutch: "dokter", english: "doctor", difficulty: "easy" },
  { dutch: "dom", english: "dumb", difficulty: "easy" },
  { dutch: "dood (zelfst. nw.)", english: "death", difficulty: "easy" },
  { dutch: "dood (bijv. nw.)", english: "dead", difficulty: "easy" },
  { dutch: "door", english: "door", difficulty: "easy" },
  { dutch: "drie", english: "three", difficulty: "easy" },
  { dutch: "drinken", english: "drink", difficulty: "easy" },
  { dutch: "dromen", english: "to dream", difficulty: "easy" },
  { dutch: "droom", english: "dream", difficulty: "easy" },
  { dutch: "dubbel", english: "double", difficulty: "easy" },
  { dutch: "dun", english: "thin", difficulty: "easy" },
  { dutch: "economie", english: "economy", difficulty: "easy" },
  { dutch: "een", english: "a", difficulty: "easy" },
  { dutch: "eerst", english: "first", difficulty: "easy" },
  { dutch: "effect", english: "effect", difficulty: "easy" },
  { dutch: "eind", english: "end", difficulty: "easy" },
  { dutch: "eindeloos", english: "endless", difficulty: "easy" },
  { dutch: "eindigen", english: "to end", difficulty: "easy" },
  { dutch: "eiland", english: "island", difficulty: "easy" },
  { dutch: "ei", english: "egg", difficulty: "easy" },
  { dutch: "elk", english: "each", difficulty: "easy" },
  { dutch: "emotie", english: "emotion", difficulty: "easy" },
  { dutch: "emotioneel", english: "emotional", difficulty: "easy" },
  { dutch: "en", english: "and", difficulty: "easy" },
  { dutch: "energie", english: "energy", difficulty: "easy" },
  { dutch: "Engels", english: "english", difficulty: "easy" },
  { dutch: "enorm", english: "enormous", difficulty: "easy" },
  { dutch: "er", english: "there", difficulty: "easy" },
  { dutch: "experiment", english: "experiment", difficulty: "easy" },
  { dutch: "fabriek", english: "factory", difficulty: "easy" },
  { dutch: "factor", english: "factor", difficulty: "easy" },
  { dutch: "familie", english: "family", difficulty: "easy" },
  { dutch: "fase", english: "phase", difficulty: "easy" },
  { dutch: "feit", english: "fact", difficulty: "easy" },
  { dutch: "figuur", english: "figure", difficulty: "easy" },
  { dutch: "film", english: "movie", difficulty: "easy" },
  { dutch: "financieel", english: "financial", difficulty: "easy" },
  { dutch: "foto", english: "photo", difficulty: "easy" },
  { dutch: "fruit", english: "fruit", difficulty: "easy" },
  { dutch: "functie", english: "function", difficulty: "easy" },
  { dutch: "fundamenteel", english: "fundamentally", difficulty: "easy" },
  { dutch: "gaan", english: "to go", difficulty: "easy" },
  { dutch: "gast", english: "guest", difficulty: "easy" },
  { dutch: "geboren", english: "born", difficulty: "easy" },
  { dutch: "geef", english: "give", difficulty: "easy" },
  { dutch: "gemeen", english: "mean", difficulty: "easy" },
  { dutch: "generatie", english: "generation", difficulty: "easy" },
  { dutch: "gevoel", english: "feeling", difficulty: "easy" },
  { dutch: "geven", english: "to give", difficulty: "easy" },
  { dutch: "glas", english: "glass", difficulty: "easy" },
  { dutch: "goed", english: "good", difficulty: "easy" },
  { dutch: "goederen", english: "goods", difficulty: "easy" },
  { dutch: "gouden", english: "golden", difficulty: "easy" },
  { dutch: "gras", english: "grass", difficulty: "easy" },
  { dutch: "groen", english: "green", difficulty: "easy" },
  { dutch: "groeien", english: "to grow", difficulty: "easy" },
  { dutch: "groep", english: "group", difficulty: "easy" },
  { dutch: "haar", english: "her", difficulty: "easy" },
  { dutch: "half", english: "half", difficulty: "easy" },
  { dutch: "hand", english: "hand", difficulty: "easy" },
  { dutch: "hard", english: "hard", difficulty: "easy" },
  { dutch: "hart", english: "heart", difficulty: "easy" },
  { dutch: "hebben", english: "to have", difficulty: "easy" },
  { dutch: "heet", english: "hot", difficulty: "easy" },
  { dutch: "helft", english: "half", difficulty: "easy" },
  { dutch: "helpen", english: "to help", difficulty: "easy" },
  { dutch: "hem", english: "him", difficulty: "easy" },
  { dutch: "het", english: "it", difficulty: "easy" },
  { dutch: "hier", english: "here", difficulty: "easy" },
  { dutch: "hij", english: "he", difficulty: "easy" },
  { dutch: "historisch", english: "historical", difficulty: "easy" },
  { dutch: "hoed", english: "hat", difficulty: "easy" },
  { dutch: "hoe", english: "how", difficulty: "easy" },
  { dutch: "Holland", english: "Holland", difficulty: "easy" },
  { dutch: "honger", english: "hungry", difficulty: "easy" },
  { dutch: "hoop", english: "hope", difficulty: "easy" },
  { dutch: "hopen", english: "to hope", difficulty: "easy" },
  { dutch: "horen", english: "to hear", difficulty: "easy" },
  { dutch: "hotel", english: "hotel", difficulty: "easy" },
  { dutch: "houden", english: "to keep", difficulty: "easy" },
  { dutch: "huis", english: "house", difficulty: "easy" },
  { dutch: "hulp", english: "help", difficulty: "easy" },
  { dutch: "hut", english: "hut", difficulty: "easy" },
  { dutch: "ideaal", english: "ideal", difficulty: "easy" },
  { dutch: "idee", english: "idea", difficulty: "easy" },
  { dutch: "ik", english: "I", difficulty: "easy" },
  { dutch: "in", english: "in", difficulty: "easy" },
  { dutch: "individu", english: "individual", difficulty: "easy" },
  { dutch: "individueel", english: "individually", difficulty: "easy" },
  { dutch: "informatie", english: "information", difficulty: "easy" },
  { dutch: "initiatief", english: "initiative", difficulty: "easy" },
  { dutch: "instrument", english: "instrument", difficulty: "easy" },
  { dutch: "interessant", english: "interesting", difficulty: "easy" },
  { dutch: "internationaal", english: "international", difficulty: "easy" },
  { dutch: "invloed", english: "influence", difficulty: "easy" },
  { dutch: "ja", english: "yes", difficulty: "easy" },
  { dutch: "jaar", english: "year", difficulty: "easy" },
  { dutch: "je", english: "you", difficulty: "easy" },
  { dutch: "jezelf", english: "yourself", difficulty: "easy" },
  { dutch: "jij", english: "you", difficulty: "easy" },
  { dutch: "jong", english: "young", difficulty: "easy" },
  { dutch: "jongeman", english: "young man", difficulty: "easy" },
  { dutch: "jou", english: "you", difficulty: "easy" },
  { dutch: "jullie", english: "you", difficulty: "easy" },
  { dutch: "juni", english: "june", difficulty: "easy" },
  { dutch: "kaas", english: "cheese", difficulty: "easy" },
  { dutch: "kalm", english: "calm", difficulty: "easy" },
  { dutch: "kamp", english: "camp", difficulty: "easy" },
  { dutch: "karakter", english: "character", difficulty: "easy" },
  { dutch: "kat", english: "cat", difficulty: "easy" },
  { dutch: "kilometer", english: "kilometers", difficulty: "easy" },
  { dutch: "kind", english: "child", difficulty: "easy" },
  { dutch: "klas", english: "class", difficulty: "easy" },
  { dutch: "klassiek", english: "classic", difficulty: "easy" },
  { dutch: "kleur", english: "color", difficulty: "easy" },
  { dutch: "klimmen", english: "to climb", difficulty: "easy" },
  { dutch: "knie", english: "knee", difficulty: "easy" },
  { dutch: "koel", english: "cool", difficulty: "easy" },
  { dutch: "koffie", english: "coffee", difficulty: "easy" },
  { dutch: "komen", english: "come", difficulty: "easy" },
  { dutch: "koning", english: "king", difficulty: "easy" },
  { dutch: "kosten", english: "to cost", difficulty: "easy" },
  { dutch: "koud", english: "cold", difficulty: "easy" },
  { dutch: "kruis", english: "cross", difficulty: "easy" },
  { dutch: "kunnen", english: "can/to be able to", difficulty: "easy" },
  { dutch: "kust", english: "coast", difficulty: "easy" },
  { dutch: "kwaliteit", english: "quality", difficulty: "easy" },
  { dutch: "laat", english: "late", difficulty: "easy" },
  { dutch: "laatste", english: "last", difficulty: "easy" },
  { dutch: "lachen", english: "laugh", difficulty: "easy" },
  { dutch: "landschap", english: "landscape", difficulty: "easy" },
  { dutch: "lang", english: "long", difficulty: "easy" },
  { dutch: "langs", english: "along", difficulty: "easy" },
  { dutch: "laten", english: "to let", difficulty: "easy" },
  { dutch: "later", english: "later", difficulty: "easy" },
  { dutch: "leider", english: "leader", difficulty: "easy" },
  { dutch: "leiden", english: "to lead", difficulty: "easy" },
  { dutch: "leiding", english: "leadership", difficulty: "easy" },
  { dutch: "leren", english: "to learn", difficulty: "easy" },
  { dutch: "leven", english: "life", difficulty: "easy" },
  { dutch: "leveren", english: "to deliver", difficulty: "easy" },
  { dutch: "licht", english: "light", difficulty: "easy" },
  { dutch: "liefde", english: "love", difficulty: "easy" },
  { dutch: "lip", english: "lip", difficulty: "easy" },
  { dutch: "literatuur", english: "literature", difficulty: "easy" },
  { dutch: "logisch", english: "logical", difficulty: "easy" },
  { dutch: "los", english: "loose", difficulty: "easy" },
  { dutch: "luisteren", english: "listen", difficulty: "easy" },
  { dutch: "luitenant", english: "lieutenant", difficulty: "easy" },
  { dutch: "maan", english: "moon", difficulty: "easy" },
  { dutch: "maand", english: "month", difficulty: "easy" },
  { dutch: "maaltijd", english: "meal", difficulty: "easy" },
  { dutch: "machine", english: "machine", difficulty: "easy" },
  { dutch: "maken", english: "to make", difficulty: "easy" },
  { dutch: "mama", english: "mom", difficulty: "easy" },
  { dutch: "man", english: "man", difficulty: "easy" },
  { dutch: "markt", english: "market", difficulty: "easy" },
  { dutch: "materiaal", english: "material", difficulty: "easy" },
  { dutch: "me", english: "me", difficulty: "easy" },
  { dutch: "medisch", english: "medical", difficulty: "easy" },
  { dutch: "meer", english: "more", difficulty: "easy" },
  { dutch: "meester", english: "master", difficulty: "easy" },
  { dutch: "meestal", english: "mostly", difficulty: "easy" },
  { dutch: "menen", english: "mean", difficulty: "easy" },
  { dutch: "meter", english: "meter", difficulty: "easy" },
  { dutch: "methode", english: "method", difficulty: "easy" },
  { dutch: "mezelf", english: "myself", difficulty: "easy" },
  { dutch: "mij", english: "me", difficulty: "easy" },
  { dutch: "mijn", english: "my", difficulty: "easy" },
  { dutch: "miljoen", english: "million", difficulty: "easy" },
  { dutch: "minister", english: "minister", difficulty: "easy" },
  { dutch: "minuut", english: "minute", difficulty: "easy" },
  { dutch: "missen", english: "to miss", difficulty: "easy" },
  { dutch: "modern", english: "modern", difficulty: "easy" },
  { dutch: "moeder", english: "mother", difficulty: "easy" },
  { dutch: "moeten", english: "should", difficulty: "easy" },
  { dutch: "moment", english: "moment", difficulty: "easy" },
  { dutch: "mond", english: "mouth", difficulty: "easy" },
  { dutch: "motief", english: "motive", difficulty: "easy" },
  { dutch: "museum", english: "museum", difficulty: "easy" },
  { dutch: "muziek", english: "music", difficulty: "easy" },
  { dutch: "naam", english: "name", difficulty: "easy" },
  { dutch: "nacht", english: "night", difficulty: "easy" },
  { dutch: "nationaal", english: "national", difficulty: "easy" },
  { dutch: "natuur", english: "nature", difficulty: "easy" },
  { dutch: "nee", english: "no", difficulty: "easy" },
  { dutch: "negatief", english: "negative", difficulty: "easy" },
  { dutch: "nek", english: "neck", difficulty: "easy" },
  { dutch: "neus", english: "nose", difficulty: "easy" },
  { dutch: "niet", english: "not", difficulty: "easy" },
  { dutch: "nieuw", english: "new", difficulty: "easy" },
  { dutch: "noorden", english: "north", difficulty: "easy" },
  { dutch: "normaal", english: "normal", difficulty: "easy" },
  { dutch: "nu", english: "now", difficulty: "easy" },
  { dutch: "nummer", english: "number", difficulty: "easy" },
  { dutch: "object", english: "object", difficulty: "easy" },
  { dutch: "of", english: "or", difficulty: "easy" },
  { dutch: "officieel", english: "officially", difficulty: "easy" },
  { dutch: "officier", english: "officer", difficulty: "easy" },
  { dutch: "oktober", english: "October", difficulty: "easy" },
  { dutch: "olie", english: "oil", difficulty: "easy" },
  { dutch: "om", english: "around", difficulty: "easy" },
  { dutch: "ontbreken", english: "lack", difficulty: "easy" },
  { dutch: "oor", english: "ear", difficulty: "easy" },
  { dutch: "open", english: "open", difficulty: "easy" },
  { dutch: "openen", english: "to open", difficulty: "easy" },
  { dutch: "operatie", english: "operation", difficulty: "easy" },
  { dutch: "op", english: "on", difficulty: "easy" },
  { dutch: "orgaan", english: "organ", difficulty: "easy" },
  { dutch: "organisatie", english: "organization", difficulty: "easy" },
  { dutch: "organiseren", english: "to organize", difficulty: "easy" },
  { dutch: "oud", english: "old", difficulty: "easy" },
  { dutch: "pijnlijk", english: "painful", difficulty: "easy" },
  { dutch: "papier", english: "paper", difficulty: "easy" },
  { dutch: "partner", english: "partner", difficulty: "easy" },
  { dutch: "passeren", english: "pass", difficulty: "easy" },
  { dutch: "patiënt", english: "patient", difficulty: "easy" },
  { dutch: "patroon", english: "pattern", difficulty: "easy" },
  { dutch: "periode", english: "period", difficulty: "easy" },
  { dutch: "pers", english: "press", difficulty: "easy" },
  { dutch: "persoon", english: "person", difficulty: "easy" },
  { dutch: "persoonlijk", english: "personally", difficulty: "easy" },
  { dutch: "persoonlijkheid", english: "personality", difficulty: "easy" },
  { dutch: "plaats", english: "place", difficulty: "easy" },
  { dutch: "plaatsen", english: "place", difficulty: "easy" },
  { dutch: "plan", english: "plan", difficulty: "easy" },
  { dutch: "plant", english: "plant", difficulty: "easy" },
  { dutch: "plezier", english: "pleasure", difficulty: "easy" },
  { dutch: "politie", english: "law enforcement", difficulty: "easy" },
  { dutch: "positie", english: "position", difficulty: "easy" },
  { dutch: "positief", english: "positive", difficulty: "easy" },
  { dutch: "pot", english: "pot", difficulty: "easy" },
  { dutch: "praktisch", english: "practical", difficulty: "easy" },
  { dutch: "praktijk", english: "practice", difficulty: "easy" },
  { dutch: "president", english: "president", difficulty: "easy" },
  { dutch: "prijs", english: "price", difficulty: "easy" },
  { dutch: "probleem", english: "problem", difficulty: "easy" },
  { dutch: "procent", english: "per cent", difficulty: "easy" },
  { dutch: "proces", english: "process", difficulty: "easy" },
  { dutch: "produceren", english: "to produce", difficulty: "easy" },
  { dutch: "productie", english: "production", difficulty: "easy" },
  { dutch: "product", english: "product", difficulty: "easy" },
  { dutch: "programma", english: "program", difficulty: "easy" },
  { dutch: "project", english: "project", difficulty: "easy" },
  { dutch: "provincie", english: "province", difficulty: "easy" },
  { dutch: "psychologisch", english: "psychological", difficulty: "easy" },
  { dutch: "psychologie", english: "psychology", difficulty: "easy" },
  { dutch: "psycholoog", english: "psychologist", difficulty: "easy" },
  { dutch: "publiceren", english: "to publish", difficulty: "easy" },
  { dutch: "radio", english: "radio", difficulty: "easy" },
  { dutch: "reactie", english: "reaction", difficulty: "easy" },
  { dutch: "realiseren", english: "realize", difficulty: "easy" },
  { dutch: "reden", english: "reason", difficulty: "easy" },
  { dutch: "relatie", english: "relationship", difficulty: "easy" },
  { dutch: "relatief", english: "relatively", difficulty: "easy" },
  { dutch: "rennen", english: "To run", difficulty: "easy" },
  { dutch: "rest", english: "rest", difficulty: "easy" },
  { dutch: "restaurant", english: "restaurant", difficulty: "easy" },
  { dutch: "resultaat", english: "result", difficulty: "easy" },
  { dutch: "rijk", english: "rich", difficulty: "easy" },
  { dutch: "risico", english: "risk", difficulty: "easy" },
  { dutch: "rivier", english: "river", difficulty: "easy" },
  { dutch: "rol", english: "role", difficulty: "easy" },
  { dutch: "rond", english: "round", difficulty: "easy" },
  { dutch: "rood", english: "red", difficulty: "easy" },
  { dutch: "rusten", english: "to rest", difficulty: "easy" },
  { dutch: "schaduw", english: "shadow", difficulty: "easy" },
  { dutch: "schoen", english: "shoe", difficulty: "easy" },
  { dutch: "school", english: "school", difficulty: "easy" },
  { dutch: "schouder", english: "shoulder", difficulty: "easy" },
  { dutch: "seconde", english: "second", difficulty: "easy" },
  { dutch: "sector", english: "sector", difficulty: "easy" },
  { dutch: "serieus", english: "serious", difficulty: "easy" },
  { dutch: "sigaret", english: "cigarette", difficulty: "easy" },
  { dutch: "sinds", english: "since", difficulty: "easy" },
  { dutch: "slaap", english: "sleep", difficulty: "easy" },
  { dutch: "slapen", english: "to sleep", difficulty: "easy" },
  { dutch: "sneeuw", english: "snow", difficulty: "easy" },
  { dutch: "sociaal", english: "social", difficulty: "easy" },
  { dutch: "sommige", english: "some", difficulty: "easy" },
  { dutch: "soms", english: "sometimes", difficulty: "easy" },
  { dutch: "soort", english: "kind", difficulty: "easy" },
  { dutch: "speciaal", english: "special", difficulty: "easy" },
  { dutch: "specifiek", english: "specific", difficulty: "easy" },
  { dutch: "spreken", english: "to speak", difficulty: "easy" },
  { dutch: "staan", english: "stand / to stand", difficulty: "easy" },
  { dutch: "staat", english: "state", difficulty: "easy" },
  { dutch: "stad", english: "city", difficulty: "easy" },
  { dutch: "stap", english: "step", difficulty: "easy" },
  { dutch: "stappen", english: "to step", difficulty: "easy" },
  { dutch: "station", english: "station", difficulty: "easy" },
  { dutch: "steen", english: "stone", difficulty: "easy" },
  { dutch: "ster", english: "star", difficulty: "easy" },
  { dutch: "stijf", english: "stiff", difficulty: "easy" },
  { dutch: "stijl", english: "style", difficulty: "easy" },
  { dutch: "stoppen", english: "stop", difficulty: "easy" },
  { dutch: "straat", english: "street", difficulty: "easy" },
  { dutch: "structuur", english: "structure", difficulty: "easy" },
  { dutch: "student", english: "student", difficulty: "easy" },
  { dutch: "studeren", english: "to study", difficulty: "easy" },
  { dutch: "studie", english: "study", difficulty: "easy" },
  { dutch: "succes", english: "good luck", difficulty: "easy" },
  { dutch: "suiker", english: "sugar", difficulty: "easy" },
  { dutch: "symbool", english: "symbol", difficulty: "easy" },
  { dutch: "systeem", english: "system", difficulty: "easy" },
  { dutch: "tafel", english: "table", difficulty: "easy" },
  { dutch: "tante", english: "aunt", difficulty: "easy" },
  { dutch: "te", english: "too", difficulty: "easy" },
  { dutch: "technisch", english: "technical", difficulty: "easy" },
  { dutch: "techniek", english: "technic", difficulty: "easy" },
  { dutch: "tee", english: "tea", difficulty: "easy" },
  { dutch: "telefoon", english: "phone", difficulty: "easy" },
  { dutch: "televisie", english: "television", difficulty: "easy" },
  { dutch: "tekst", english: "text", difficulty: "easy" },
  { dutch: "terug", english: "back", difficulty: "easy" },
  { dutch: "terrein", english: "terrain", difficulty: "easy" },
  { dutch: "terras", english: "terrace", difficulty: "easy" },
  { dutch: "theorie", english: "theory", difficulty: "easy" },
  { dutch: "theoretisch", english: "theoretically", difficulty: "easy" },
  { dutch: "tien", english: "ten", difficulty: "easy" },
  { dutch: "tijd", english: "time", difficulty: "easy" },
  { dutch: "titel", english: "title", difficulty: "easy" },
  { dutch: "toen", english: "then (past)", difficulty: "easy" },
  { dutch: "tong", english: "tongue", difficulty: "easy" },
  { dutch: "top", english: "top", difficulty: "easy" },
  { dutch: "totaal", english: "total", difficulty: "easy" },
  { dutch: "traditie", english: "tradition", difficulty: "easy" },
  { dutch: "traditioneel", english: "traditional", difficulty: "easy" },
  { dutch: "trein", english: "train", difficulty: "easy" },
  { dutch: "twee", english: "two", difficulty: "easy" },
  { dutch: "typisch", english: "typical", difficulty: "easy" },
  { dutch: "u", english: "you", difficulty: "easy" },
  { dutch: "uur", english: "hour", difficulty: "easy" },
  { dutch: "universiteit", english: "university", difficulty: "easy" },
  { dutch: "vader", english: "father", difficulty: "easy" },
  { dutch: "vallen", english: "fall", difficulty: "easy" },
  { dutch: "vechten", english: "to fight", difficulty: "easy" },
  { dutch: "veld", english: "field", difficulty: "easy" },
  { dutch: "ver", english: "far", difficulty: "easy" },
  { dutch: "verbieden", english: "to forbid", difficulty: "easy" },
  { dutch: "verder", english: "further", difficulty: "easy" },
  { dutch: "vertellen", english: "to tell", difficulty: "easy" },
  { dutch: "vervullen", english: "fulfill", difficulty: "easy" },
  { dutch: "verspreiden", english: "to spread", difficulty: "easy" },
  { dutch: "vier", english: "four", difficulty: "easy" },
  { dutch: "vijf", english: "five", difficulty: "easy" },
  { dutch: "vinden", english: "find", difficulty: "easy" },
  { dutch: "vinger", english: "finger", difficulty: "easy" },
  { dutch: "vis", english: "fish", difficulty: "easy" },
  { dutch: "visie", english: "vision", difficulty: "easy" },
  { dutch: "vliegen", english: "fly", difficulty: "easy" },
  { dutch: "vloer", english: "floor", difficulty: "easy" },
  { dutch: "vluchten", english: "to flee", difficulty: "easy" },
  { dutch: "voet", english: "foot", difficulty: "easy" },
  { dutch: "voelen", english: "to feel", difficulty: "easy" },
  { dutch: "vol", english: "full", difficulty: "easy" },
  { dutch: "voor", english: "before", difficulty: "easy" },
  { dutch: "vorming", english: "formation", difficulty: "easy" },
  { dutch: "vrij", english: "free", difficulty: "easy" },
  { dutch: "vriend", english: "friend", difficulty: "easy" },
  { dutch: "vriendelijk", english: "friendly", difficulty: "easy" },
  { dutch: "vullen", english: "to fill", difficulty: "easy" },
  { dutch: "vuur", english: "fire", difficulty: "easy" },
  { dutch: "wachten", english: "to wait", difficulty: "easy" },
  { dutch: "wakker", english: "awake", difficulty: "easy" },
  { dutch: "wanneer", english: "when", difficulty: "easy" },
  { dutch: "wapen", english: "weapon", difficulty: "easy" },
  { dutch: "warm", english: "warm", difficulty: "easy" },
  { dutch: "warmte", english: "warmth", difficulty: "easy" },
  { dutch: "water", english: "water", difficulty: "easy" },
  { dutch: "week", english: "week", difficulty: "easy" },
  { dutch: "weg", english: "road", difficulty: "easy" },
  { dutch: "wel", english: "well", difficulty: "easy" },
  { dutch: "werk", english: "work", difficulty: "easy" },
  { dutch: "werken", english: "to work", difficulty: "easy" },
  { dutch: "wereld", english: "world", difficulty: "easy" },
  { dutch: "wet", english: "law", difficulty: "easy" },
  { dutch: "wetenschap", english: "science", difficulty: "easy" },
  { dutch: "wetenschappelijk", english: "scientific", difficulty: "easy" },
  { dutch: "wie", english: "who", difficulty: "easy" },
  { dutch: "wijn", english: "wine", difficulty: "easy" },
  { dutch: "wij", english: "we", difficulty: "easy" },
  { dutch: "willen", english: "to want", difficulty: "easy" },
  { dutch: "wind", english: "wind", difficulty: "easy" },
  { dutch: "winkel", english: "shop", difficulty: "easy" },
  { dutch: "woord", english: "word", difficulty: "easy" },
  { dutch: "woordenboek", english: "dictionary", difficulty: "easy" },
  { dutch: "wonen", english: "to live", difficulty: "easy" },
  { dutch: "woning", english: "residence", difficulty: "easy" },
  { dutch: "woud", english: "forest", difficulty: "easy" },
  { dutch: "wraak", english: "revenge", difficulty: "easy" },
  { dutch: "wrijven", english: "to rub", difficulty: "easy" },
  { dutch: "zacht", english: "soft", difficulty: "easy" },
  { dutch: "zak", english: "bag", difficulty: "easy" },
  { dutch: "zand", english: "sand", difficulty: "easy" },
  { dutch: "ze", english: "they", difficulty: "easy" },
  { dutch: "zee", english: "sea", difficulty: "easy" },
  { dutch: "zeggen", english: "to say", difficulty: "easy" },
  { dutch: "zelf", english: "self", difficulty: "easy" },
  { dutch: "zeker", english: "sure", difficulty: "easy" },
  { dutch: "zelfstandig", english: "independent", difficulty: "easy" },
  { dutch: "zender", english: "transmitter", difficulty: "easy" },
  { dutch: "zetten", english: "to put", difficulty: "easy" },
  { dutch: "zich", english: "himself/herself", difficulty: "easy" },
  { dutch: "ziek", english: "sick", difficulty: "easy" },
  { dutch: "zien", english: "to see", difficulty: "easy" },
  { dutch: "zilver", english: "silver", difficulty: "easy" },
  { dutch: "zingen", english: "to sing", difficulty: "easy" },
  { dutch: "zin", english: "sentence", difficulty: "easy" },
  { dutch: "zitten", english: "to sit", difficulty: "easy" },
  { dutch: "zo", english: "so", difficulty: "easy" },
  { dutch: "zoeken", english: "to search", difficulty: "easy" },
  { dutch: "zoet", english: "sweet", difficulty: "easy" },
  { dutch: "zomer", english: "summer", difficulty: "easy" },
  { dutch: "zon", english: "sun", difficulty: "easy" },
  { dutch: "zonder", english: "without", difficulty: "easy" },
  { dutch: "zorg", english: "care", difficulty: "easy" },
  { dutch: "zorgen", english: "to care", difficulty: "easy" },
  { dutch: "zout", english: "salt", difficulty: "easy" },
  { dutch: "zowel", english: "as well as", difficulty: "easy" },
  { dutch: "zullen", english: "shall", difficulty: "easy" },
  { dutch: "zus", english: "sister", difficulty: "easy" },
  { dutch: "zwart", english: "black", difficulty: "easy" },
  { dutch: "zwemmen", english: "to swim", difficulty: "easy" },
  { dutch: "boom", english: "tree", difficulty: "medium" },
  { dutch: "stoel", english: "chair", difficulty: "medium" },
  { dutch: "van", english: "from / of", difficulty: "medium" },
  { dutch: "zijn", english: "to be", difficulty: "medium" },
  { dutch: "met", english: "with", difficulty: "medium" },
  { dutch: "als", english: "if/when", difficulty: "medium" },
  { dutch: "er", english: "there", difficulty: "medium" },
  { dutch: "maar", english: "but", difficulty: "medium" },
  { dutch: "om", english: "around", difficulty: "medium" },
  { dutch: "naar", english: "to", difficulty: "medium" },
  { dutch: "ook", english: "also", difficulty: "medium" },
  { dutch: "bij", english: "at", difficulty: "medium" },
  { dutch: "nog", english: "yet", difficulty: "medium" },
  { dutch: "tot", english: "until", difficulty: "medium" },
  { dutch: "ons/onze", english: "our", difficulty: "medium" },
  { dutch: "veel", english: "many", difficulty: "medium" },
  { dutch: "mens", english: "human", difficulty: "medium" },
  { dutch: "toch", english: "however", difficulty: "medium" },
  { dutch: "na", english: "after", difficulty: "medium" },
  { dutch: "tijd", english: "time", difficulty: "medium" },
  { dutch: "kind", english: "child", difficulty: "medium" },
  { dutch: "vrouw", english: "woman", difficulty: "medium" },
  { dutch: "oog", english: "eye", difficulty: "medium" },
  { dutch: "dus", english: "so", difficulty: "medium" },
  { dutch: "heel", english: "very", difficulty: "medium" },
  { dutch: "even", english: "for a bit, for a while", difficulty: "medium" },
  { dutch: "zelfs", english: "even", difficulty: "medium" },
  { dutch: "elk", english: "each", difficulty: "medium" },
  { dutch: "ver", english: "far", difficulty: "medium" },
  { dutch: "hoofd", english: "head", difficulty: "medium" },
  { dutch: "zeer, heel", english: "very", difficulty: "medium" },
  { dutch: "een paar", english: "a couple", difficulty: "medium" },
  { dutch: "vraag", english: "question", difficulty: "medium" },
  { dutch: "vaak", english: "often", difficulty: "medium" },
  { dutch: "keer", english: "times", difficulty: "medium" },
  { dutch: "eerst", english: "first", difficulty: "medium" },
  { dutch: "weg", english: "away", difficulty: "medium" },
  { dutch: "zaak", english: "matter, business", difficulty: "medium" },
  { dutch: "net", english: "just", difficulty: "medium" },
  { dutch: "heen", english: "away", difficulty: "medium" },
  { dutch: "hoog", english: "high", difficulty: "medium" },
  { dutch: "juist", english: "right", difficulty: "medium" },
  { dutch: "sterk", english: "strong", difficulty: "medium" },
  { dutch: "waar", english: "true", difficulty: "medium" },
  { dutch: "deel", english: "part", difficulty: "medium" },
  { dutch: "snel", english: "fast", difficulty: "medium" },
  { dutch: "mooi", english: "beautiful, pretty", difficulty: "medium" },
  { dutch: "feit", english: "fact", difficulty: "medium" },
  { dutch: "zin", english: "sentence", difficulty: "medium" },
  { dutch: "kort", english: "short", difficulty: "medium" },
  { dutch: "vast", english: "fixed", difficulty: "medium" },
  { dutch: "stad", english: "city", difficulty: "medium" },
  { dutch: "vroeg", english: "early", difficulty: "medium" },
  { dutch: "stem", english: "voice", difficulty: "medium" },
  { dutch: "kant", english: "side", difficulty: "medium" },
  { dutch: "geld", english: "money", difficulty: "medium" },
  { dutch: "stuk", english: "piece", difficulty: "medium" },
  { dutch: "graag", english: "gladly", difficulty: "medium" },
  { dutch: "nou", english: "well", difficulty: "medium" },
  { dutch: "pas", english: "only", difficulty: "medium" },
  { dutch: "recht", english: "straight", difficulty: "medium" },
  { dutch: "zwaar", english: "heavy", difficulty: "medium" },
  { dutch: "lid", english: "member", difficulty: "medium" },
  { dutch: "eeuw", english: "century", difficulty: "medium" },
  { dutch: "mond", english: "mouth", difficulty: "medium" },
  { dutch: "opnieuw", english: "again", difficulty: "medium" },
  { dutch: "thuis", english: "at home", difficulty: "medium" },
  { dutch: "kracht", english: "power", difficulty: "medium" },
  { dutch: "ooit", english: "ever", difficulty: "medium" },
  { dutch: "kerk", english: "church", difficulty: "medium" },
  { dutch: "blik", english: "look", difficulty: "medium" },
  { dutch: "kans", english: "opportunity", difficulty: "medium" },
  { dutch: "brief", english: "letter", difficulty: "medium" },
  { dutch: "beeld", english: "statue", difficulty: "medium" },
  { dutch: "zacht", english: "soft", difficulty: "medium" },
  { dutch: "macht", english: "power", difficulty: "medium" },
  { dutch: "via / door", english: "through", difficulty: "medium" },
  { dutch: "gang", english: "corridor", difficulty: "medium" },
  { dutch: "been", english: "leg", difficulty: "medium" },
  { dutch: "slecht", english: "bad", difficulty: "medium" },
  { dutch: "wet", english: "law", difficulty: "medium" },
  { dutch: "bang", english: "afraid", difficulty: "medium" },
  { dutch: "dier", english: "animal", difficulty: "medium" },
  { dutch: "lucht", english: "sky", difficulty: "medium" },
  { dutch: "rug", english: "back", difficulty: "medium" },
  { dutch: "angst", english: "fear", difficulty: "medium" },
  { dutch: "laag", english: "low", difficulty: "medium" },
  { dutch: "raam", english: "window", difficulty: "medium" },
  { dutch: "hond", english: "dog", difficulty: "medium" },
  { dutch: "stil", english: "quiet", difficulty: "medium" },
  { dutch: "doel", english: "target", difficulty: "medium" },
  { dutch: "dienst", english: "shift", difficulty: "medium" },
  { dutch: "zwart", english: "black", difficulty: "medium" },
  { dutch: "menen", english: "mean", difficulty: "medium" },
  { dutch: "dik", english: "fat", difficulty: "medium" },
  { dutch: "paard", english: "horse", difficulty: "medium" },
  { dutch: "vreemd", english: "strange", difficulty: "medium" },
  { dutch: "taal", english: "language", difficulty: "medium" },
  { dutch: "volk", english: "people", difficulty: "medium" },
  { dutch: "aarde", english: "soil", difficulty: "medium" },
  { dutch: "stoel", english: "chair", difficulty: "medium" },
  { dutch: "muur", english: "wall", difficulty: "medium" },
  { dutch: "raad", english: "advice", difficulty: "medium" },
  { dutch: "boom", english: "tree", difficulty: "medium" },
  { dutch: "dorp", english: "village", difficulty: "medium" },
  { dutch: "breed", english: "wide", difficulty: "medium" },
  { dutch: "leeg", english: "empty", difficulty: "medium" },
  { dutch: "lief", english: "sweet", difficulty: "medium" },
  { dutch: "klaar", english: "ready", difficulty: "medium" },
  { dutch: "zorg", english: "care", difficulty: "medium" },
  { dutch: "gauw", english: "soon", difficulty: "medium" },
  { dutch: "trap", english: "stairs", difficulty: "medium" },
  { dutch: "gek", english: "crazy", difficulty: "medium" },
  { dutch: "blad", english: "sheet", difficulty: "medium" },
  { dutch: "spel", english: "game", difficulty: "medium" },
  { dutch: "zak", english: "bag", difficulty: "medium" },
  { dutch: "borst", english: "chest", difficulty: "medium" },
  { dutch: "hoop", english: "pile", difficulty: "medium" },
  { dutch: "fles", english: "bottle", difficulty: "medium" },
  { dutch: "grens", english: "border", difficulty: "medium" },
  { dutch: "hoek", english: "corner", difficulty: "medium" },
  { dutch: "oom", english: "uncle", difficulty: "medium" },
  { dutch: "vlak", english: "flat", difficulty: "medium" },
  { dutch: "buurt", english: "neighborhood", difficulty: "medium" },
  { dutch: "ruim", english: "spacious", difficulty: "medium" },
  { dutch: "blij", english: "happy", difficulty: "medium" },
  { dutch: "eten", english: "food", difficulty: "medium" },
  { dutch: "stof", english: "dust", difficulty: "medium" },
  { dutch: "gat", english: "hole", difficulty: "medium" },
  { dutch: "boer", english: "farmer", difficulty: "medium" },
  { dutch: "reis", english: "trip, journey", difficulty: "medium" },
  { dutch: "druk", english: "busy", difficulty: "medium" },
  { dutch: "druk", english: "pressure", difficulty: "medium" },
  { dutch: "vlug / snel", english: "quickly", difficulty: "medium" },
  { dutch: "schuld", english: "debt", difficulty: "medium" },
  { dutch: "leuk", english: "fun", difficulty: "medium" },
  { dutch: "bloem", english: "flower", difficulty: "medium" },
  { dutch: "huisarts", english: "doctor", difficulty: "medium" },
  { dutch: "fijn", english: "nice", difficulty: "medium" },
  { dutch: "links", english: "left", difficulty: "medium" },
  { dutch: "plek", english: "place", difficulty: "medium" },
  { dutch: "niks", english: "nothing", difficulty: "medium" },
  { dutch: "tand", english: "tooth", difficulty: "medium" },
  { dutch: "rand", english: "edge", difficulty: "medium" },
  { dutch: "bos", english: "forest", difficulty: "medium" },
  { dutch: "rust", english: "peace/calm", difficulty: "medium" },
  { dutch: "kring", english: "circle", difficulty: "medium" },
  { dutch: "grijs", english: "gray", difficulty: "medium" },
  { dutch: "haast", english: "rush", difficulty: "medium" },
  { dutch: "vlees", english: "meat", difficulty: "medium" },
  { dutch: "eis", english: "demand", difficulty: "medium" },
  { dutch: "streek", english: "region", difficulty: "medium" },
  { dutch: "smaak", english: "taste", difficulty: "medium" },
  { dutch: "traan", english: "tear", difficulty: "medium" },
  { dutch: "rij", english: "queue", difficulty: "medium" },
  { dutch: "spoor", english: "track", difficulty: "medium" },
  { dutch: "last", english: "burden", difficulty: "medium" },
  { dutch: "smal", english: "narrow", difficulty: "medium" },
  { dutch: "slot", english: "key lock", difficulty: "medium" },
  { dutch: "zwak", english: "weak", difficulty: "medium" },
  { dutch: "geur", english: "smell", difficulty: "medium" },
  { dutch: "buik", english: "stomach", difficulty: "medium" },
  { dutch: "flink", english: "hefty", difficulty: "medium" },
  { dutch: "beurt", english: "turn", difficulty: "medium" },
  { dutch: "wangen", english: "cheeks", difficulty: "medium" },
  { dutch: "vloer", english: "floor", difficulty: "medium" },
  { dutch: "rook", english: "smoke", difficulty: "medium" },
  { dutch: "slag", english: "battle", difficulty: "medium" },
  { dutch: "maan", english: "moon", difficulty: "medium" },
  { dutch: "wens", english: "wish", difficulty: "medium" },
  { dutch: "sfeer", english: "ambiance", difficulty: "medium" },
  { dutch: "bron", english: "source", difficulty: "medium" },
  { dutch: "rijk", english: "rich", difficulty: "medium" },
  { dutch: "droog", english: "dry", difficulty: "medium" },
  { dutch: "bord", english: "plate", difficulty: "medium" },
  { dutch: "jeugd", english: "youth", difficulty: "medium" },
  { dutch: "schoon", english: "clean", difficulty: "medium" },
  { dutch: "keel", english: "throat", difficulty: "medium" },
  { dutch: "pak", english: "business suit", difficulty: "medium" },
  { dutch: "broek", english: "pants", difficulty: "medium" },
  { dutch: "golf", english: "wave", difficulty: "medium" },
  { dutch: "lichaam", english: "body", difficulty: "medium" },
  { dutch: "groei", english: "growth", difficulty: "medium" },
  { dutch: "nat", english: "wet", difficulty: "medium" },
  { dutch: "duur", english: "expensive", difficulty: "medium" },
  { dutch: "feest", english: "party", difficulty: "medium" },
  { dutch: "reeks", english: "series", difficulty: "medium" },
  { dutch: "strak", english: "tight", difficulty: "medium" },
  { dutch: "kleed", english: "carpet", difficulty: "medium" },
  { dutch: "vlucht", english: "flight", difficulty: "medium" },
  { dutch: "dak", english: "roof", difficulty: "medium" },
  { dutch: "hals", english: "neck", difficulty: "medium" },
  { dutch: "geel", english: "yellow", difficulty: "medium" },
  { dutch: "streng", english: "strict", difficulty: "medium" },
  { dutch: "veld", english: "field", difficulty: "medium" },
  { dutch: "moe", english: "tired", difficulty: "medium" },
  { dutch: "geloof", english: "faith, belief", difficulty: "medium" },
  { dutch: "tak", english: "branch", difficulty: "medium" },
  { dutch: "tong", english: "tongue", difficulty: "medium" },
  { dutch: "kwijt", english: "lost", difficulty: "medium" },
  { dutch: "kaas", english: "cheese", difficulty: "medium" },
  { dutch: "zaal", english: "hall", difficulty: "medium" },
  { dutch: "greep", english: "grip", difficulty: "medium" },
  { dutch: "kust", english: "coast", difficulty: "medium" },
  { dutch: "boos", english: "angry", difficulty: "medium" },
  { dutch: "brug", english: "bridge", difficulty: "medium" },
  { dutch: "vak", english: "field, subject", difficulty: "medium" },
  { dutch: "strand", english: "beach", difficulty: "medium" },
  { dutch: "klant", english: "customer", difficulty: "medium" },
  { dutch: "fout", english: "mistake", difficulty: "medium" },
  { dutch: "moed", english: "courage", difficulty: "medium" },
  { dutch: "dom", english: "stupid", difficulty: "medium" },
  { dutch: "jas", english: "jacket", difficulty: "medium" },
  { dutch: "trots", english: "pride", difficulty: "medium" },
  { dutch: "zoet", english: "sweet", difficulty: "medium" },
  { dutch: "fiets", english: "bicycle", difficulty: "medium" },
  { dutch: "wolk", english: "cloud", difficulty: "medium" },
  { dutch: "kast", english: "closet", difficulty: "medium" },
  { dutch: "klap", english: "blow", difficulty: "medium" },
  { dutch: "stroom", english: "flow", difficulty: "medium" },
  { dutch: "winst", english: "profit", difficulty: "medium" },
  { dutch: "knap", english: "good looking", difficulty: "medium" },
  { dutch: "straf", english: "punishment", difficulty: "medium" },
  { dutch: "langzaam", english: "slow", difficulty: "medium" },
  { dutch: "boog", english: "bow", difficulty: "medium" },
  { dutch: "een poos", english: "a while", difficulty: "medium" },
  { dutch: "strekken", english: "stretch", difficulty: "medium" },
  { dutch: "brand", english: "fire", difficulty: "medium" },
  { dutch: "dwars", english: "transverse", difficulty: "medium" },
  { dutch: "kist", english: "chest", difficulty: "medium" },
  { dutch: "wand", english: "wall", difficulty: "medium" },
  { dutch: "klacht", english: "complaint", difficulty: "medium" },
  { dutch: "stuur", english: "steering wheel", difficulty: "medium" },
  { dutch: "kern", english: "core", difficulty: "medium" },
  { dutch: "leer", english: "leather", difficulty: "medium" },
  { dutch: "het liefst", english: "most preferably", difficulty: "medium" },
  { dutch: "dun", english: "thin", difficulty: "medium" },
  { dutch: "jurk", english: "dress", difficulty: "medium" },
  { dutch: "troep", english: "mess", difficulty: "medium" },
  { dutch: "hoed", english: "hat", difficulty: "medium" },
  { dutch: "sturen", english: "to send", difficulty: "medium" },
  { dutch: "tocht", english: "tour", difficulty: "medium" },
  { dutch: "mes", english: "knife", difficulty: "medium" },
  { dutch: "maat", english: "measure", difficulty: "medium" },
  { dutch: "poot", english: "leg", difficulty: "medium" },
  { dutch: "vent", english: "guy", difficulty: "medium" },
  { dutch: "maag", english: "stomach", difficulty: "medium" },
  { dutch: "lijk", english: "corpse", difficulty: "medium" },
  { dutch: "eer", english: "honor", difficulty: "medium" },
  { dutch: "mooi", english: "beautiful", difficulty: "medium" },
  { dutch: "kruis", english: "cross", difficulty: "medium" },
  { dutch: "doos", english: "box", difficulty: "medium" },
  { dutch: "vrucht", english: "fruit", difficulty: "medium" },
  { dutch: "klein", english: "small", difficulty: "medium" },
  { dutch: "makkelijk", english: "easy", difficulty: "medium" },
  { dutch: "eigenlijk", english: "actually", difficulty: "hard" },
  { dutch: "misschien", english: "maybe", difficulty: "hard" },
  { dutch: "over", english: "about", difficulty: "hard" },
  { dutch: "ander", english: "other", difficulty: "hard" },
  { dutch: "zoals", english: "such as", difficulty: "hard" },
  { dutch: "zonder", english: "without", difficulty: "hard" },
  { dutch: "altijd", english: "always", difficulty: "hard" },
  { dutch: "eigen", english: "own", difficulty: "hard" },
  { dutch: "alles", english: "everything", difficulty: "hard" },
  { dutch: "terwijl", english: "while", difficulty: "hard" },
  { dutch: "anders", english: "different", difficulty: "hard" },
  { dutch: "terug", english: "back", difficulty: "hard" },
  { dutch: "mogelijk", english: "possible", difficulty: "hard" },
  { dutch: "geval", english: "case", difficulty: "hard" },
  { dutch: "echter", english: "however", difficulty: "hard" },
  { dutch: "zeker", english: "sure", difficulty: "hard" },
  { dutch: "enkel", english: "only", difficulty: "hard" },
  { dutch: "natuurlijk", english: "of course", difficulty: "hard" },
  { dutch: "gezicht", english: "face", difficulty: "hard" },
  { dutch: "iemand", english: "someone", difficulty: "hard" },
  { dutch: "wereld", english: "world", difficulty: "hard" },
  { dutch: "duidelijk", english: "clearly", difficulty: "hard" },
  { dutch: "vooral", english: "mostly", difficulty: "hard" },
  { dutch: "nodig", english: "required", difficulty: "hard" },
  { dutch: "bijna", english: "almost", difficulty: "hard" },
  { dutch: "alsof", english: "as if", difficulty: "hard" },
  { dutch: "helemaal", english: "completely", difficulty: "hard" },
  { dutch: "binnen", english: "within, inside", difficulty: "hard" },
  { dutch: "aantal", english: "number of", difficulty: "hard" },
  { dutch: "manier", english: "way", difficulty: "hard" },
  { dutch: "kamer", english: "room", difficulty: "hard" },
  { dutch: "allemaal", english: "all of them", difficulty: "hard" },
  { dutch: "zichzelf", english: "himself", difficulty: "hard" },
  { dutch: "eigenlijk", english: "actually", difficulty: "hard" },
  { dutch: "niemand", english: "nobody", difficulty: "hard" },
  { dutch: "daarom", english: "therefore", difficulty: "hard" },
  { dutch: "gewoon", english: "just", difficulty: "hard" },
  { dutch: "samen", english: "together", difficulty: "hard" },
  { dutch: "genoeg", english: "enough", difficulty: "hard" },
  { dutch: "verder", english: "further", difficulty: "hard" },
  { dutch: "daarna", english: "after that", difficulty: "hard" },
  { dutch: "verschillende", english: "various", difficulty: "hard" },
  { dutch: "volgens", english: "according to", difficulty: "hard" },
  { dutch: "moeilijk", english: "difficult", difficulty: "hard" },
  { dutch: "weinig", english: "little, few", difficulty: "hard" },
  { dutch: "iedereen", english: "everyone", difficulty: "hard" },
  { dutch: "dezelfde", english: "the same", difficulty: "hard" },
  { dutch: "gedachte", english: "thought", difficulty: "hard" },
  { dutch: "geheel", english: "whole", difficulty: "hard" },
  { dutch: "bijvoorbeeld", english: "for example", difficulty: "hard" },
  { dutch: "belang", english: "interest", difficulty: "hard" },
  { dutch: "ontwikkeling", english: "development", difficulty: "hard" },
  { dutch: "zoveel", english: "that much", difficulty: "hard" },
  { dutch: "gevoel", english: "feeling", difficulty: "hard" },
  { dutch: "boven", english: "upstairs", difficulty: "hard" },
  { dutch: "algemeen", english: "general", difficulty: "hard" },
  { dutch: "gebied", english: "area", difficulty: "hard" },
  { dutch: "bijzonder", english: "special", difficulty: "hard" },
  { dutch: "buiten", english: "outside", difficulty: "hard" },
  { dutch: "verhaal", english: "story", difficulty: "hard" },
  { dutch: "gevolg", english: "consequence", difficulty: "hard" },
  { dutch: "voorbeeld", english: "example", difficulty: "hard" },
  { dutch: "opnieuw", english: "again", difficulty: "hard" },
  { dutch: "vroeger", english: "back in the days", difficulty: "hard" },
  { dutch: "bovendien", english: "moreover", difficulty: "hard" },
  { dutch: "mogelijkheid", english: "possibility", difficulty: "hard" },
  { dutch: "reden", english: "reason", difficulty: "hard" },
  { dutch: "eerder", english: "earlier", difficulty: "hard" },
  { dutch: "bepaald", english: "determined", difficulty: "hard" },
  { dutch: "vanuit", english: "from", difficulty: "hard" },
  { dutch: "tegenover", english: "opposite", difficulty: "hard" },
  { dutch: "gebruik", english: "use", difficulty: "hard" },
  { dutch: "meteen", english: "right away", difficulty: "hard" },
  { dutch: "onderzoek", english: "research", difficulty: "hard" },
  { dutch: "beweging", english: "movement", difficulty: "hard" },
  { dutch: "waarschijnlijk", english: "probably", difficulty: "hard" },
  { dutch: "zaken", english: "affairs", difficulty: "hard" },
  { dutch: "aandacht", english: "attention", difficulty: "hard" },
  { dutch: "langzaam", english: "slowly", difficulty: "hard" },
  { dutch: "richting", english: "towards", difficulty: "hard" },
  { dutch: "verschillen", english: "differences", difficulty: "hard" },
  { dutch: "oorlog", english: "war", difficulty: "hard" },
  { dutch: "meestal", english: "mostly", difficulty: "hard" },
  { dutch: "nauwelijks", english: "barely", difficulty: "hard" },
  { dutch: "hetzelfde", english: "the same", difficulty: "hard" },
  { dutch: "tenslotte", english: "finally", difficulty: "hard" },
  { dutch: "menselijk", english: "human", difficulty: "hard" },
  { dutch: "invloed", english: "influence", difficulty: "hard" },
  { dutch: "bezig", english: "busy", difficulty: "hard" },
  { dutch: "verband", english: "bandage", difficulty: "hard" },
  { dutch: "plotseling", english: "suddenly", difficulty: "hard" },
  { dutch: "inderdaad", english: "indeed", difficulty: "hard" },
  { dutch: "maatschappij", english: "society", difficulty: "hard" },
  { dutch: "gemakkelijk", english: "easy", difficulty: "hard" },
  { dutch: "donker", english: "dark", difficulty: "hard" },
  { dutch: "verschil", english: "difference", difficulty: "hard" },
  { dutch: "gelukkig", english: "happy", difficulty: "hard" },
  { dutch: "betekenis", english: "meaning", difficulty: "hard" },
  { dutch: "ervaring", english: "experience", difficulty: "hard" },
  { dutch: "begrip", english: "understanding", difficulty: "hard" },
  { dutch: "mevrouw", english: "Mrs.", difficulty: "hard" },
  { dutch: "volgende", english: "next", difficulty: "hard" },
  { dutch: "volledig", english: "complete", difficulty: "hard" },
  { dutch: "verschillend", english: "different", difficulty: "hard" },
  { dutch: "onderwijs", english: "education", difficulty: "hard" },
  { dutch: "behoefte", english: "need", difficulty: "hard" },
  { dutch: "rustig", english: "quiet", difficulty: "hard" },
  { dutch: "eenmaal", english: "once", difficulty: "hard" },
  { dutch: "eenvoudig", english: "simple", difficulty: "hard" },
  { dutch: "ongeveer", english: "approximately", difficulty: "hard" },
  { dutch: "waarde", english: "value", difficulty: "hard" },
  { dutch: "ergens", english: "somewhere", difficulty: "hard" },
  { dutch: "gesprek", english: "conversation", difficulty: "hard" },
  { dutch: "indruk", english: "impression", difficulty: "hard" },
  { dutch: "aarde", english: "soil", difficulty: "hard" },
  { dutch: "onmiddellijk", english: "immediately", difficulty: "hard" },
  { dutch: "werkelijkheid", english: "reality", difficulty: "hard" },
  { dutch: "persoonlijk", english: "in person", difficulty: "hard" },
  { dutch: "ruimte", english: "space", difficulty: "hard" },
  { dutch: "moeite", english: "effort", difficulty: "hard" },
  { dutch: "verandering", english: "change", difficulty: "hard" },
  { dutch: "geluid", english: "sound", difficulty: "hard" },
  { dutch: "gedrag", english: "behaviour", difficulty: "hard" },
  { dutch: "bewust", english: "conscious", difficulty: "hard" },
  { dutch: "namelijk", english: "namely", difficulty: "hard" },
  { dutch: "regel", english: "rule", difficulty: "hard" },
  { dutch: "voordat", english: "before", difficulty: "hard" },
  { dutch: "gelijk", english: "equal", difficulty: "hard" },
  { dutch: "geschiedenis", english: "history", difficulty: "hard" },
  { dutch: "kop", english: "headline", difficulty: "hard" },
  { dutch: "voldoende", english: "enough", difficulty: "hard" },
  { dutch: "overal", english: "everywhere", difficulty: "hard" },
  { dutch: "ernstig", english: "serious", difficulty: "hard" },
  { dutch: "nogal", english: "quite", difficulty: "hard" },
  { dutch: "overigens", english: "moreover", difficulty: "hard" },
  { dutch: "omstandigheid", english: "circumstance", difficulty: "hard" },
  { dutch: "noch", english: "neither", difficulty: "hard" },
  { dutch: "trouwens", english: "besides, by the way", difficulty: "hard" },
  { dutch: "toekomst", english: "future", difficulty: "hard" },
  { dutch: "opeens", english: "suddenly", difficulty: "hard" },
  { dutch: "omgeving", english: "surroundings", difficulty: "hard" },
  { dutch: "opvatting", english: "view", difficulty: "hard" },
  { dutch: "overheid", english: "government", difficulty: "hard" },
  { dutch: "afstand", english: "distance", difficulty: "hard" },
  { dutch: "vervolgens", english: "thereafter", difficulty: "hard" },
  { dutch: "wetenschap", english: "science", difficulty: "hard" },
  { dutch: "ondanks", english: "despite", difficulty: "hard" },
  { dutch: "eindelijk", english: "finally", difficulty: "hard" },
  { dutch: "vrijheid", english: "freedom", difficulty: "hard" },
  { dutch: "omhoog", english: "up", difficulty: "hard" },
  { dutch: "ziekte", english: "disease", difficulty: "hard" },
  { dutch: "hoogte", english: "height", difficulty: "hard" },
  { dutch: "beleid", english: "policy", difficulty: "hard" },
  { dutch: "schrijver", english: "writer", difficulty: "hard" },
  { dutch: "maatschappij", english: "society", difficulty: "hard" },
  { dutch: "bedrijf", english: "company", difficulty: "hard" },
  { dutch: "beneden", english: "down", difficulty: "hard" },
  { dutch: "vandaag", english: "today", difficulty: "hard" },
  { dutch: "samenleving", english: "society", difficulty: "hard" },
  { dutch: "verhouding", english: "ratio", difficulty: "hard" },
  { dutch: "houding", english: "attitude", difficulty: "hard" },
  { dutch: "gevaar", english: "danger", difficulty: "hard" },
  { dutch: "regering", english: "government", difficulty: "hard" },
  { dutch: "rekening", english: "bill", difficulty: "hard" },
  { dutch: "wetenschappelijk", english: "scientific", difficulty: "hard" },
  { dutch: "soldaat", english: "soldier", difficulty: "hard" },
  { dutch: "waarheid", english: "truth", difficulty: "hard" },
  { dutch: "tenminste", english: "at least", difficulty: "hard" },
  { dutch: "prachtig", english: "magnificent", difficulty: "hard" },
  { dutch: "beroep", english: "profession", difficulty: "hard" },
  { dutch: "poging", english: "attempt", difficulty: "hard" },
  { dutch: "oorzaak", english: "cause", difficulty: "hard" },
  { dutch: "mening", english: "opinion", difficulty: "hard" },
  { dutch: "allen", english: "all", difficulty: "hard" },
  { dutch: "gezin", english: "family", difficulty: "hard" },
  { dutch: "voorzichtig", english: "careful", difficulty: "hard" },
  { dutch: "beslissing", english: "decision", difficulty: "hard" },
  { dutch: "uiteindelijk", english: "in the end", difficulty: "hard" },
  { dutch: "geleden", english: "ago", difficulty: "hard" },
  { dutch: "gelegenheid", english: "opportunity", difficulty: "hard" },
  { dutch: "noodzakelijk", english: "necessary", difficulty: "hard" },
  { dutch: "aanwezig", english: "present", difficulty: "hard" },
  { dutch: "leeftijd", english: "age", difficulty: "hard" },
  { dutch: "bellen", english: "dial", difficulty: "hard" },
  { dutch: "onmogelijk", english: "impossible", difficulty: "hard" },
  { dutch: "stilte", english: "silence", difficulty: "hard" },
  { dutch: "behandeling", english: "therapy", difficulty: "hard" },
  { dutch: "huwelijk", english: "wedding", difficulty: "hard" },
  { dutch: "vorige", english: "last, previous", difficulty: "hard" },
  { dutch: "verklaring", english: "statement", difficulty: "hard" },
  { dutch: "verleden", english: "past", difficulty: "hard" },
  { dutch: "bezoek", english: "visit", difficulty: "hard" },
  { dutch: "oplossing", english: "solution", difficulty: "hard" },
  { dutch: "doordat", english: "because", difficulty: "hard" },
  { dutch: "verlangen", english: "desire", difficulty: "hard" },
  { dutch: "bevatten", english: "contain", difficulty: "hard" },
  { dutch: "moeilijkheid", english: "difficulty", difficulty: "hard" },
  { dutch: "keuken", english: "kitchen", difficulty: "hard" },
  { dutch: "herinnering", english: "reminder", difficulty: "hard" },
  { dutch: "dagelijks", english: "daily", difficulty: "hard" },
  { dutch: "ziekenhuis", english: "hospital", difficulty: "hard" },
  { dutch: "zodra", english: "as soon as", difficulty: "hard" },
  { dutch: "onderwerp", english: "topic, subject", difficulty: "hard" },
  { dutch: "vrijwel", english: "almost", difficulty: "hard" },
  { dutch: "blijkbaar", english: "apparently", difficulty: "hard" },
  { dutch: "bureau", english: "desk", difficulty: "hard" },
  { dutch: "opdracht", english: "assignment, exercise", difficulty: "hard" },
  { dutch: "gebouw", english: "building", difficulty: "hard" },
  { dutch: "uitdrukking", english: "expression", difficulty: "hard" },
  { dutch: "zolang", english: "as long as", difficulty: "hard" },
  { dutch: "lekker", english: "tasty, nice", difficulty: "hard" },
  { dutch: "bestuur", english: "board", difficulty: "hard" },
  { dutch: "keuze", english: "choice", difficulty: "hard" },
  { dutch: "behalve", english: "except", difficulty: "hard" },
  { dutch: "uitspraak", english: "pronunciation", difficulty: "hard" },
  { dutch: "nergens", english: "nowhere", difficulty: "hard" },
  { dutch: "gezond", english: "healthy", difficulty: "hard" },
  { dutch: "voorstel", english: "proposal", difficulty: "hard" },
  { dutch: "veilig", english: "safe", difficulty: "hard" },
  { dutch: "stijgen", english: "rise", difficulty: "hard" },
  { dutch: "besluit", english: "decision", difficulty: "hard" },
  { dutch: "eiland", english: "island", difficulty: "hard" },
  { dutch: "tegenstelling", english: "contrary", difficulty: "hard" },
  { dutch: "oordeel", english: "judgment", difficulty: "hard" },
  { dutch: "twijfel", english: "doubt", difficulty: "hard" },
  { dutch: "glimlach", english: "smile", difficulty: "hard" },
  { dutch: "uitsluitend", english: "exclusively", difficulty: "hard" },
  { dutch: "wellicht", english: "perhaps", difficulty: "hard" },
  { dutch: "spanning", english: "tension, stress", difficulty: "hard" },
  { dutch: "arbeid", english: "labor", difficulty: "hard" },
  { dutch: "gevaarlijk", english: "dangerous", difficulty: "hard" },
  { dutch: "rechter", english: "judge", difficulty: "hard" },
  { dutch: "leraar", english: "teacher", difficulty: "hard" },
  { dutch: "vriendin", english: "girlfriend", difficulty: "hard" },
  { dutch: "zekerheid", english: "security", difficulty: "hard" },
  { dutch: "gewoonlijk", english: "usually", difficulty: "hard" },
  { dutch: "heerlijk", english: "delicious", difficulty: "hard" },
  { dutch: "geur", english: "smell", difficulty: "hard" },
  { dutch: "openbaar", english: "public", difficulty: "hard" },
  { dutch: "voordeel", english: "benefit", difficulty: "hard" },
  { dutch: "opmerking", english: "comment", difficulty: "hard" },
  { dutch: "intussen", english: "meanwhile", difficulty: "hard" },
  { dutch: "gezag", english: "authority", difficulty: "hard" },
  { dutch: "herhalen", english: "to repeat", difficulty: "hard" },
  { dutch: "tevreden", english: "satisfied; pleased", difficulty: "hard" },
  { dutch: "kantoor", english: "office", difficulty: "hard" },
  { dutch: "gedeelte", english: "part", difficulty: "hard" },
  { dutch: "afdeling", english: "department", difficulty: "hard" },
  { dutch: "maatregel", english: "measure", difficulty: "hard" },
  { dutch: "voedsel", english: "food", difficulty: "hard" },
  { dutch: "boodschap", english: "message", difficulty: "hard" },
  { dutch: "krachtige", english: "powerful", difficulty: "hard" },
  { dutch: "vrolijk", english: "cheerful", difficulty: "hard" },
  { dutch: "vertrek", english: "departure", difficulty: "hard" },
  { dutch: "toevallig", english: "coincidentally", difficulty: "hard" },
  { dutch: "uitstekend", english: "excellent; outstanding", difficulty: "hard" },
  { dutch: "bewijs", english: "proof", difficulty: "hard" },
  { dutch: "voorkeur", english: "preference", difficulty: "hard" },
  { dutch: "achtergrond", english: "background", difficulty: "hard" },
  { dutch: "eigenschap", english: "charachteristic", difficulty: "hard" },
  { dutch: "bezit", english: "possession", difficulty: "hard" },
  { dutch: "handeling", english: "act", difficulty: "hard" },
  { dutch: "arbeider", english: "worker", difficulty: "hard" },
  { dutch: "prettig", english: "pleasant", difficulty: "hard" },
  { dutch: "geheim", english: "secret", difficulty: "hard" },
  { dutch: "gedicht", english: "poem", difficulty: "hard" },
  { dutch: "vijand", english: "enemy", difficulty: "hard" },
  { dutch: "verwachting", english: "expectation", difficulty: "hard" },
  { dutch: "inmiddels", english: "in the meantime", difficulty: "hard" },
  { dutch: "ongetwijfeld", english: "undoubtedly, surely", difficulty: "hard" },
  { dutch: "vergadering", english: "meeting", difficulty: "hard" },
  { dutch: "buitenlands", english: "foreign", difficulty: "hard" },
  { dutch: "opleiding", english: "education", difficulty: "hard" },
  { dutch: "verschrikkelijk", english: "terrible", difficulty: "hard" },
  { dutch: "ambtenaar", english: "civil servant", difficulty: "hard" },
  { dutch: "redelijk", english: "reasonable, reasonably", difficulty: "hard" },
  { dutch: "gewoonte", english: "habit", difficulty: "hard" },
  { dutch: "verzoek", english: "request", difficulty: "hard" },
  { dutch: "leerling", english: "pupil", difficulty: "hard" },
  { dutch: "geweld", english: "violence", difficulty: "hard" },
  { dutch: "uitzondering", english: "exception", difficulty: "hard" },
  { dutch: "voorwerp", english: "object", difficulty: "hard" },
  { dutch: "gunstig", english: "favorable", difficulty: "hard" },
  { dutch: "regeling", english: "regulation", difficulty: "hard" },
  { dutch: "doelstelling", english: "goal, objective", difficulty: "hard" },
  { dutch: "verdriet", english: "sadness", difficulty: "hard" },
  { dutch: "dichtbij", english: "nearby", difficulty: "hard" },
  { dutch: "afspraak", english: "appointment", difficulty: "hard" },
  { dutch: "allebei", english: "both", difficulty: "hard" },
  { dutch: "heuvel", english: "hill", difficulty: "hard" },
  { dutch: "voorhoofd", english: "forehead", difficulty: "hard" },
  { dutch: "vreselijk", english: "horrible", difficulty: "hard" },
  { dutch: "vrede", english: "peace", difficulty: "hard" },
  { dutch: "godsdienst", english: "religion", difficulty: "hard" },
  { dutch: "samenwerking", english: "cooperation", difficulty: "hard" },
  { dutch: "spiegel", english: "mirror", difficulty: "hard" },
  { dutch: "verstand", english: "wit, wiseness", difficulty: "hard" },
  { dutch: "onderscheid", english: "difference, distinction", difficulty: "hard" },
  { dutch: "aanval", english: "attack", difficulty: "hard" },
  { dutch: "ongeluk", english: "accident", difficulty: "hard" },
  { dutch: "sleutel", english: "key", difficulty: "hard" },
  { dutch: "koffer", english: "suitcase", difficulty: "hard" },
  { dutch: "afscheid", english: "goodbye", difficulty: "hard" },
  { dutch: "vereniging", english: "association, club", difficulty: "hard" },
  { dutch: "geweldig", english: "awesome, great", difficulty: "hard" },
  { dutch: "bodem", english: "bottom, ground", difficulty: "hard" },
  { dutch: "woning", english: "house", difficulty: "hard" },
  { dutch: "overeenkomst", english: "agreement", difficulty: "hard" },
  { dutch: "voorzitter", english: "chairman", difficulty: "hard" },
  { dutch: "milieu", english: "environment", difficulty: "hard" },
  { dutch: "kenmerken", english: "characteristics", difficulty: "hard" },
  { dutch: "landschap", english: "landscape", difficulty: "hard" },
  { dutch: "definitief", english: "final", difficulty: "hard" },
  { dutch: "nauwkeurig", english: "accurate", difficulty: "hard" },
  { dutch: "bijdrage", english: "contribution", difficulty: "hard" },
  { dutch: "overleg", english: "consultation", difficulty: "hard" },
  { dutch: "man, echtgenoot", english: "husband", difficulty: "hard" },
  { dutch: "verbazing", english: "surprise", difficulty: "hard" },
  { dutch: "gordijnen", english: "curtains", difficulty: "hard" },
  { dutch: "goedkoop", english: "cheap", difficulty: "hard" },
  { dutch: "evenwicht", english: "balance", difficulty: "hard" },
  { dutch: "vochtig", english: "moist", difficulty: "hard" },
  { dutch: "vergelijking", english: "comparison", difficulty: "hard" },
  { dutch: "gezondheid", english: "health", difficulty: "hard" },
  { dutch: "kern", english: "core", difficulty: "hard" },
  { dutch: "gevangenis", english: "jail, prison", difficulty: "hard" },
  { dutch: "slaapkamer", english: "bedroom", difficulty: "hard" },
  { dutch: "kleren", english: "clothes", difficulty: "hard" },
  { dutch: "makkelijk", english: "easy", difficulty: "hard" },
  { dutch: "verbaasd", english: "surprised", difficulty: "hard" },
  { dutch: "deken", english: "blanket", difficulty: "hard" },
  { dutch: "vreugde", english: "joy", difficulty: "hard" },
  { dutch: "gemak", english: "ease", difficulty: "hard" },
  { dutch: "kunstenaar", english: "artist", difficulty: "hard" },
  { dutch: "burgemeester", english: "mayor", difficulty: "hard" },
  { dutch: "verlies", english: "loss", difficulty: "hard" },
  { dutch: "burgerlijk", english: "civil", difficulty: "hard" },
  { dutch: "lelijk", english: "ugly", difficulty: "hard" },
  { dutch: "overig", english: "other, remaining", difficulty: "hard" },
  { dutch: "bereid", english: "prepared", difficulty: "hard" },
  { dutch: "koningin", english: "queen", difficulty: "hard" },
  { dutch: "eigenaar", english: "owner", difficulty: "hard" },
  { dutch: "ontmoeting", english: "meeting", difficulty: "hard" },
  { dutch: "verslag", english: "report", difficulty: "hard" },
  { dutch: "onverwacht", english: "unexpected", difficulty: "hard" },
  { dutch: "personeel", english: "staff", difficulty: "hard" },
  { dutch: "gezellig", english: "cozy", difficulty: "hard" },
  { dutch: "geheugen", english: "memory", difficulty: "hard" },
  { dutch: "verdrietig", english: "sad", difficulty: "hard" },
  { dutch: "snelheid", english: "speed", difficulty: "hard" },
  { dutch: "gemeen", english: "mean", difficulty: "hard" },
  { dutch: "nuttig", english: "helpful; useful", difficulty: "hard" },
  { dutch: "schade", english: "damage", difficulty: "hard" },
  { dutch: "kapot", english: "broken", difficulty: "hard" },
  { dutch: "bescherming", english: "protection", difficulty: "hard" },
  { dutch: "noodzaak", english: "need", difficulty: "hard" },
  { dutch: "jammer", english: "unfortunately", difficulty: "hard" },
  { dutch: "toekomstig", english: "future", difficulty: "hard" },
  { dutch: "tijdschrift", english: "magazine", difficulty: "hard" },
  { dutch: "verdieping", english: "floor", difficulty: "hard" },
  { dutch: "aantrekkelijk", english: "attractive", difficulty: "hard" },
  { dutch: "opvoeding", english: "education", difficulty: "hard" },
  { dutch: "tegenstander", english: "opponent", difficulty: "hard" },
  { dutch: "verantwoordelijkheid", english: "responsibility", difficulty: "hard" }
];
